// lib/content/tools.ts
import type { Tool } from "@/lib/data-types";

export const tools: Tool[] = [
  {
    id: "t1",
    slug: "cursor",
    name: "Cursor",
    oneLiner: "AI-first editor that makes refactors feel less like punishment.",
    useCases: ["Refactor safely", "Generate scaffolds", "Navigate large codebases"],
    pros: ["Great codebase context UX", "Fast iteration loop", "Useful diffs/edits workflow"],
    cons: ["Still hallucinates", "Can encourage sloppy review habits"],
    pricing: { tier: "freemium", note: "Free tier + paid plans" },
    alternatives: [
      { name: "VS Code + AI", slug: "vscode-ai" },
      { name: "JetBrains AI", slug: "jetbrains-ai" },
    ],
    tags: ["dev", "coding", "editor"],
    updatedAtISO: "2026-01-21",
  },
  {
    id: "t2",
    slug: "perplexity",
    name: "Perplexity",
    oneLiner: "Search + answers that can cite sources when you demand it politely.",
    useCases: ["Research fast", "Compare viewpoints", "Find starting sources"],
    pros: ["Quick scanning", "Good for discovery", "Useful summaries"],
    cons: ["Citations can be messy", "Not a substitute for reading"],
    pricing: { tier: "freemium" },
    alternatives: [
      { name: "Kagi", slug: "kagi" },
      { name: "Google", slug: "google" },
    ],
    tags: ["search", "research", "productivity"],
    updatedAtISO: "2026-01-20",
  },
  {
    id: "t3",
    slug: "notion-ai",
    name: "Notion AI",
    oneLiner: "Draft, summarize, and clean up docs without leaving your workspace.",
    useCases: ["Summarize notes", "Draft docs", "Rewrite text"],
    pros: ["Lives where your docs are", "Good for drafting", "Team-friendly"],
    cons: ["Can be generic", "Costs scale with usage"],
    pricing: { tier: "paid", note: "Add-on pricing varies" },
    alternatives: [
      { name: "Google Docs AI", slug: "google-docs-ai" },
      { name: "Craft", slug: "craft" },
    ],
    tags: ["writing", "notes", "team"],
    updatedAtISO: "2026-01-19",
  },
  {
    id: "t4",
    slug: "elevenlabs",
    name: "ElevenLabs",
    oneLiner: "Voice generation for creators, narration, and apps (use responsibly).",
    useCases: ["Voiceovers", "Dubbing", "Character voices"],
    pros: ["High quality voices", "Lots of languages", "Creator-friendly workflow"],
    cons: ["Costs scale", "Voice ethics/legal risk if abused"],
    pricing: { tier: "freemium" },
    alternatives: [
      { name: "PlayHT", slug: "playht" },
      { name: "Azure TTS", slug: "azure-tts" },
    ],
    tags: ["audio", "voice", "creator"],
    updatedAtISO: "2026-01-18",
  },
  {
    id: "t5",
    slug: "runpod",
    name: "RunPod",
    oneLiner: "Rent GPUs without selling a kidney. Useful for ML experiments.",
    useCases: ["GPU notebooks", "Model inference", "Training bursts"],
    pros: ["Simple GPU access", "Good for experiments", "Pay-as-you-go vibe"],
    cons: ["Costs can spike", "You still need DevOps brain cells"],
    pricing: { tier: "paid", note: "Usage-based compute" },
    alternatives: [
      { name: "Paperspace", slug: "paperspace" },
      { name: "Vast.ai", slug: "vast-ai" },
    ],
    tags: ["gpu", "ml", "infra"],
    updatedAtISO: "2026-01-17",
  },
  {
    id: "t6",
    slug: "langfuse",
    name: "Langfuse",
    oneLiner: "LLM observability: traces, evals, and why your agent went rogue.",
    useCases: ["Trace LLM calls", "Evaluate outputs", "Debug agents"],
    pros: ["Great visibility", "Team workflows", "Makes issues reproducible"],
    cons: ["Setup overhead", "You still need good eval design"],
    pricing: { tier: "freemium", note: "Self-host + cloud options" },
    alternatives: [
      { name: "Helicone", slug: "helicone" },
      { name: "LangSmith", slug: "langsmith" },
    ],
    tags: ["llm", "observability", "agents"],
    updatedAtISO: "2026-01-16",
  },
  {
    id: "t7",
    slug: "zotero",
    name: "Zotero",
    oneLiner: "Reference manager for research that doesn’t hate you back.",
    useCases: ["Manage citations", "Organize papers", "Collaborate on reading lists"],
    pros: ["Solid ecosystem", "Works offline", "Good citation support"],
    cons: ["Sync limits on free", "UI feels academic"],
    pricing: { tier: "freemium" },
    alternatives: [
      { name: "Mendeley", slug: "mendeley" },
      { name: "Paperpile", slug: "paperpile" },
    ],
    tags: ["research", "citations", "writing"],
    updatedAtISO: "2026-01-15",
  },
  {
    id: "t8",
    slug: "excalidraw",
    name: "Excalidraw",
    oneLiner: "Sketch diagrams that look handmade, not corporate.",
    useCases: ["System diagrams", "Quick wireframes", "Explain ideas visually"],
    pros: ["Fast", "Shareable", "Low friction"],
    cons: ["Not for pixel-perfect design", "Can get messy on huge boards"],
    pricing: { tier: "freemium" },
    alternatives: [
      { name: "FigJam", slug: "figjam" },
      { name: "Miro", slug: "miro" },
    ],
    tags: ["diagrams", "design", "productivity"],
    updatedAtISO: "2026-01-14",
  },
  {
    id: "t9",
    slug: "obsidian",
    name: "Obsidian",
    oneLiner: "Local-first knowledge base for people who hoard ideas.",
    useCases: ["Second brain", "Study notes", "Personal wiki"],
    pros: ["Offline-first", "Plugin ecosystem", "Fast search"],
    cons: ["Can turn into a hobby", "Sync is extra"],
    pricing: { tier: "freemium", note: "Optional paid sync" },
    alternatives: [
      { name: "Notion", slug: "notion" },
      { name: "Logseq", slug: "logseq" },
    ],
    tags: ["notes", "productivity", "knowledge"],
    updatedAtISO: "2026-01-13",
  },
  {
    id: "t10",
    slug: "framer",
    name: "Framer",
    oneLiner: "Ship landing pages fast with animations that don’t look tragic.",
    useCases: ["Landing pages", "Prototypes", "Marketing sites"],
    pros: ["Fast publishing", "Great templates", "Smooth interactions"],
    cons: ["Can be pricey", "Less flexible than custom code"],
    pricing: { tier: "freemium" },
    alternatives: [
      { name: "Webflow", slug: "webflow" },
      { name: "Carrd", slug: "carrd" },
    ],
    tags: ["design", "marketing", "website"],
    updatedAtISO: "2026-01-12",
  },
];
