// lib/content/tools.ts
import type { Tool } from "@/lib/data-types";

export const tools: Tool[] = [
  {
    id: "t1",
    slug: "cursor",
    name: "Cursor",
    oneLiner: "AI-first editor that makes refactors feel less like punishment.",
    description:
      "Cursor is a code editor built around AI workflows (multi-file edits, codebase-wide context, and agent-style changes). It shines when you want to ship faster, but still need reviewable diffs.",
    useCases: [
      "Refactor across multiple files",
      "Generate scaffolds safely",
      "Navigate large codebases",
      "Draft tests and small utilities",
    ],
    pros: [
      "Strong codebase-context UX",
      "Fast iteration loop",
      "Great diff/patch workflow",
      "Multi-file editing and agent flows",
    ],
    cons: [
      "Still makes confident mistakes",
      "Can encourage sloppy review habits",
      "Paid tiers can add up if you live in it",
    ],
    pricing: {
      tier: "freemium",
      note: "Free Hobby tier + paid tiers (Pro and above). Pro is commonly listed at $20/mo; higher tiers expand limits and context windows.",
    },
    alternatives: [
      { name: "VS Code + Copilot", slug: "vscode-copilot" },
      { name: "JetBrains AI", slug: "jetbrains-ai" },
      { name: "Windsurf", slug: "windsurf" },
    ],
    tags: ["dev", "coding", "editor", "ai-native"],
    rating: 4.6,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t2",
    slug: "perplexity",
    name: "Perplexity",
    oneLiner: "Search + answers that can cite sources when you force it to behave.",
    description:
      "Perplexity is an answer-first search experience that can cite sources and help you explore a topic quickly. Best used as a launchpad, not a replacement for reading.",
    useCases: ["Research fast", "Compare viewpoints", "Find starting sources", "Summarize articles"],
    pros: ["Fast discovery", "Useful summaries", "Good for brainstorming queries", "Often includes citations"],
    cons: ["Citations can be uneven", "Still requires verification", "Paid tier cost may not be worth it for casual use"],
    pricing: { tier: "freemium", note: "Free tier + paid plans", details: "Paid plans add higher limits and model access." },
    alternatives: [
      { name: "Kagi", slug: "kagi" },
      { name: "Google", slug: "google" },
      { name: "Bing", slug: "bing" },
    ],
    tags: ["search", "research", "productivity"],
    rating: 4.3,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t3",
    slug: "notion-ai",
    name: "Notion AI",
    oneLiner: "Draft, summarize, and clean up docs without leaving your workspace.",
    description:
      "Notion AI adds drafting, summarization, and writing help inside Notion. Best when your notes, tasks, and docs already live there.",
    useCases: ["Summarize notes", "Draft docs", "Rewrite text", "Meeting summaries", "Turn notes into action items"],
    pros: ["Zero context switching", "Good for drafting", "Team-friendly", "Works inside docs/databases"],
    cons: ["Outputs can be generic", "Not the best for deep technical accuracy", "Pricing/availability varies by plan"],
    pricing: { tier: "paid", note: "Notion plans (AI availability varies by plan/workspace)" },
    alternatives: [
      { name: "Google Docs AI", slug: "google-docs-ai" },
      { name: "Craft", slug: "craft" },
      { name: "Coda", slug: "coda" },
    ],
    tags: ["writing", "notes", "team", "productivity"],
    rating: 4.0,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t4",
    slug: "elevenlabs",
    name: "ElevenLabs",
    oneLiner: "Voice generation for creators, narration, and apps (use responsibly).",
    description:
      "ElevenLabs is a leading AI voice platform for voiceovers, dubbing, and character voices, with strong quality and creator-focused workflows.",
    useCases: ["Voiceovers", "Dubbing", "Character voices", "Audiobook narration", "Podcast intros"],
    pros: ["High quality voices", "Good language coverage", "Creator-friendly UX", "Strong tooling ecosystem"],
    cons: ["Costs scale with usage", "Ethics/legal risk if abused", "Quality varies by language/accent"],
    pricing: { tier: "freemium", note: "Free tier + paid plans", details: "Plans differ by usage/limits; check official tiers." },
    alternatives: [
      { name: "PlayHT", slug: "playht" },
      { name: "Azure TTS", slug: "azure-tts" },
      { name: "Resemble AI", slug: "resemble-ai" },
    ],
    tags: ["audio", "voice", "creator", "content"],
    rating: 4.6,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t5",
    slug: "runpod",
    name: "RunPod",
    oneLiner: "Rent GPUs without selling a kidney. Useful for ML experiments.",
    description:
      "RunPod is a cloud GPU platform for ML training and inference. Good for bursty workloads and experiments when you don't want long-term commitments.",
    useCases: ["GPU notebooks", "Model inference", "Training bursts", "Fine-tuning models", "Serverless inference"],
    pros: ["Fast GPU access", "Flexible pricing model", "Good for experiments", "Templates and tooling"],
    cons: ["Costs can spike fast", "You still need DevOps competence", "Availability varies by region/GPU"],
    pricing: { tier: "paid", note: "Usage-based GPU pricing", details: "Costs vary heavily by GPU type and region." },
    alternatives: [
      { name: "Vast.ai", slug: "vast-ai" },
      { name: "Lambda", slug: "lambda" },
      { name: "Paperspace", slug: "paperspace" },
    ],
    tags: ["gpu", "ml", "infra", "cloud"],
    rating: 4.4,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t6",
    slug: "langfuse",
    name: "Langfuse",
    oneLiner: "LLM observability: traces, evals, and why your agent went rogue.",
    description:
      "Langfuse is an open-source LLM engineering platform: tracing, prompt management, evaluations, and monitoring for AI apps and agents.",
    useCases: ["Trace LLM calls", "Evaluate outputs", "Debug agents", "Monitor costs", "A/B test prompts"],
    pros: ["Great visibility", "Self-hostable option", "Team workflows", "Makes issues reproducible"],
    cons: ["Setup overhead", "Evals still require good design", "Learning curve for teams new to observability"],
    pricing: { tier: "freemium", note: "Free tier + paid cloud; self-host option", details: "Cloud pricing is usage-based with base plan tiers." },
    alternatives: [
      { name: "LangSmith", slug: "langsmith" },
      { name: "Helicone", slug: "helicone" },
      { name: "W&B Weave", slug: "wandb-weave" },
    ],
    tags: ["llm", "observability", "agents", "dev"],
    rating: 4.5,
    users: "Growing",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t7",
    slug: "zotero",
    name: "Zotero",
    oneLiner: "Reference manager for research that doesn't hate you back.",
    description:
      "Zotero is a free, open-source reference manager for papers, citations, and bibliographies. A staple for students and researchers.",
    useCases: ["Manage citations", "Organize papers", "Collaborate on reading lists", "Generate bibliographies"],
    pros: ["Free and reliable", "Works offline", "Great citation support", "Browser extension"],
    cons: ["Free sync storage is limited", "UI feels academic", "Mobile experience is okay, not amazing"],
    pricing: { tier: "freemium", note: "Free app + paid sync storage plans" },
    alternatives: [
      { name: "Mendeley", slug: "mendeley" },
      { name: "Paperpile", slug: "paperpile" },
      { name: "EndNote", slug: "endnote" },
    ],
    tags: ["research", "citations", "writing", "academic"],
    rating: 4.3,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t8",
    slug: "excalidraw",
    name: "Excalidraw",
    oneLiner: "Sketch diagrams that look handmade, not corporate.",
    description:
      "Excalidraw is a virtual whiteboard for quick, hand-drawn style diagrams. Perfect for docs, systems thinking, and explaining ideas fast.",
    useCases: ["System diagrams", "Quick wireframes", "Explain ideas visually", "Architecture planning"],
    pros: ["Fast", "Shareable", "Low friction", "Collaboration", "Great for docs"],
    cons: ["Not for pixel-perfect design", "Huge boards can get messy", "Limited styling options"],
    pricing: { tier: "freemium", note: "Free core + team features available" },
    alternatives: [
      { name: "FigJam", slug: "figjam" },
      { name: "Miro", slug: "miro" },
      { name: "tldraw", slug: "tldraw" },
    ],
    tags: ["diagrams", "design", "productivity", "collaboration"],
    rating: 4.7,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t9",
    slug: "obsidian",
    name: "Obsidian",
    oneLiner: "Local-first knowledge base for people who hoard ideas.",
    description:
      "Obsidian is a local-first knowledge base on Markdown files with powerful linking and plugins. Great for building a personal wiki or study system.",
    useCases: ["Second brain", "Study notes", "Personal wiki", "Daily journaling", "Knowledge management"],
    pros: ["Offline-first", "Plugin ecosystem", "Fast search", "Markdown files", "Flexible organization"],
    cons: ["Can become a hobby", "Sync is paid", "Steep learning curve if you over-customize"],
    pricing: { tier: "freemium", note: "Free app + paid Sync/Publish add-ons", details: "Sync is commonly listed around $4–$5/mo depending on billing." },
    alternatives: [
      { name: "Notion", slug: "notion" },
      { name: "Logseq", slug: "logseq" },
      { name: "Roam Research", slug: "roam" },
    ],
    tags: ["notes", "productivity", "knowledge", "pkm"],
    rating: 4.8,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t10",
    slug: "framer",
    name: "Framer",
    oneLiner: "Ship landing pages fast with animations that don't look tragic.",
    description:
      "Framer is a design-to-site builder with strong interactions, templates, and CMS. Great for marketing pages and quick launches without writing code.",
    useCases: ["Landing pages", "Marketing sites", "Portfolios", "Prototypes", "Content sites"],
    pros: ["Fast publishing", "Good templates", "Smooth interactions", "Built-in CMS", "Strong SEO basics"],
    cons: ["Can get pricey as you scale", "Less flexible than custom code", "Complex interactions have a learning curve"],
    pricing: { tier: "freemium", note: "Free plan + paid upgrades for custom domains and higher limits" },
    alternatives: [
      { name: "Webflow", slug: "webflow" },
      { name: "Carrd", slug: "carrd" },
      { name: "Typedream", slug: "typedream" },
    ],
    tags: ["design", "marketing", "website", "no-code"],
    rating: 4.6,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t11",
    slug: "midjourney",
    name: "Midjourney",
    oneLiner: "Generate images that make people ask 'wait, that's AI?'",
    description:
      "Midjourney is a top-tier image generator known for strong aesthetics and style. It's popular for concept art and marketing visuals.",
    useCases: ["Concept art", "Marketing visuals", "Creative exploration", "Mood boards"],
    pros: ["High aesthetic quality", "Strong style results", "Large community", "Regular improvements"],
    cons: ["Workflow can be awkward (Discord)", "No real free tier", "Not ideal for precise edits"],
    pricing: { tier: "paid", note: "Subscription-based" },
    alternatives: [
      { name: "DALL·E", slug: "dalle" },
      { name: "Stable Diffusion", slug: "stable-diffusion" },
      { name: "Leonardo", slug: "leonardo" },
    ],
    tags: ["image", "ai", "design", "creator"],
    rating: 4.5,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t12",
    slug: "raycast",
    name: "Raycast",
    oneLiner: "Launcher that makes your Mac feel like it has superpowers.",
    description:
      "Raycast is a macOS launcher with extensions, clipboard history, snippets, automation, and optional AI features. Big time-saver if you live on keyboard shortcuts.",
    useCases: ["Quick actions", "Clipboard manager", "Window/workflow actions", "Run scripts", "Search apps/files fast"],
    pros: ["Very fast", "Great extensions", "Polished UX", "Keyboard-first workflow"],
    cons: ["macOS only", "Can be overwhelming at first", "Some features are paid"],
    pricing: { tier: "freemium", note: "Free core + paid upgrade for advanced features" },
    alternatives: [
      { name: "Alfred", slug: "alfred" },
      { name: "Spotlight", slug: "spotlight" },
    ],
    tags: ["productivity", "mac", "launcher", "tools"],
    rating: 4.9,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t13",
    slug: "kagi",
    name: "Kagi",
    oneLiner: "Paid search for people who hate ads and love control.",
    description:
      "Kagi is a premium search engine focused on clean results, customization, and removing spam. Great if Google results feel like a landfill.",
    useCases: ["High-signal search", "Research", "Cleaner results", "Power-user search workflows"],
    pros: ["Less spam/SEO sludge", "Strong controls and filters", "Good for deep research"],
    cons: ["Paid", "Not everyone needs it", "Results can vary by region/topic"],
    pricing: { tier: "paid", note: "Subscription-based" },
    alternatives: [{ name: "Google", slug: "google" }, { name: "Perplexity", slug: "perplexity" }],
    tags: ["search", "research", "productivity"],
    rating: 4.4,
    users: "Niche",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t14",
    slug: "google",
    name: "Google Search",
    oneLiner: "The necessary mess. Best for breadth, worst for peace.",
    description:
      "Still the widest index for the open web. Great when you need coverage, but you'll do more filtering yourself.",
    useCases: ["Broad research", "Finding official sources", "Local info", "Long-tail queries"],
    pros: ["Unmatched breadth", "Lots of niche results", "Strong for navigational searches"],
    cons: ["Ads and SEO spam", "More effort to filter", "Results can be inconsistent"],
    pricing: { tier: "free", note: "Free" },
    alternatives: [{ name: "Kagi", slug: "kagi" }, { name: "Bing", slug: "bing" }],
    tags: ["search", "research"],
    rating: 4.1,
    users: "Everyone",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t15",
    slug: "vscode-copilot",
    name: "VS Code + GitHub Copilot",
    oneLiner: "Most flexible dev setup, if you don't install 47 extensions you'll regret.",
    description:
      "VS Code with Copilot gives strong inline suggestions and chat assistance while keeping you in the most popular editor ecosystem.",
    useCases: ["Autocomplete", "Small refactors", "Boilerplate generation", "Quick explanations"],
    pros: ["Huge extension ecosystem", "Familiar workflow", "Good code suggestions"],
    cons: ["Context can be weaker than AI-native editors", "Setup drift between machines/teams"],
    pricing: { tier: "paid", note: "Copilot is paid; VS Code is free" },
    alternatives: [{ name: "Cursor", slug: "cursor" }, { name: "JetBrains AI", slug: "jetbrains-ai" }],
    tags: ["dev", "coding", "editor"],
    rating: 4.4,
    users: "Massive",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t16",
    slug: "jetbrains-ai",
    name: "JetBrains AI",
    oneLiner: "Convenient AI inside IntelliJ/WebStorm for people already deep in JetBrains.",
    description:
      "JetBrains AI integrates into JetBrains IDEs for code generation, explanation, and assistance without switching tools.",
    useCases: ["Refactors in JetBrains", "Code understanding", "Inline suggestions", "IDE-native workflows"],
    pros: ["Fits JetBrains workflow", "Strong IDE features + AI", "Good for large projects"],
    cons: ["Best value only if you already use JetBrains", "Not always the fastest for quick edits"],
    pricing: { tier: "paid", note: "Paid add-on / plan-based (varies by IDE/license)" },
    alternatives: [{ name: "Cursor", slug: "cursor" }, { name: "VS Code + Copilot", slug: "vscode-copilot" }],
    tags: ["dev", "coding", "editor"],
    rating: 4.2,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t17",
    slug: "windsurf",
    name: "Windsurf",
    oneLiner: "Another AI-native coding environment competing for your attention span.",
    description:
      "Windsurf is part of the new wave of AI-first coding tools. It's aimed at faster multi-file edits and agent-style workflows.",
    useCases: ["Agentic coding", "Multi-file changes", "Repo exploration", "Rapid prototyping"],
    pros: ["AI-native workflow", "Good for fast iterations"],
    cons: ["Tooling is evolving fast", "You still need careful reviews"],
    pricing: { tier: "freemium", note: "Plans vary" },
    alternatives: [{ name: "Cursor", slug: "cursor" }, { name: "VS Code + Copilot", slug: "vscode-copilot" }],
    tags: ["dev", "coding", "ai-native"],
    rating: 4.1,
    users: "Growing",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t18",
    slug: "chatgpt",
    name: "ChatGPT",
    oneLiner: "General-purpose AI assistant for writing, coding, planning, and fixing your chaos.",
    description:
      "ChatGPT is a general AI assistant that can help with coding, writing, reasoning, and structured outputs. Best when you give clear constraints.",
    useCases: ["Drafting", "Debugging", "Planning", "Learning", "Structured output generation"],
    pros: ["Very flexible", "Good tool support in some environments", "Strong for structured prompts"],
    cons: ["Needs good prompts", "Can be confidently wrong", "Varies by model/settings"],
    pricing: { tier: "freemium", note: "Free tier + paid plans" },
    alternatives: [{ name: "Claude", slug: "claude" }, { name: "Gemini", slug: "gemini" }],
    tags: ["ai", "assistant", "productivity"],
    rating: 4.5,
    users: "Massive",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t19",
    slug: "claude",
    name: "Claude",
    oneLiner: "Strong writing + careful reasoning, especially when you want fewer hallucinations.",
    description:
      "Claude is an AI assistant often praised for clean writing and more cautious responses. Great for editing, analysis, and long-form drafting.",
    useCases: ["Writing and editing", "Summarization", "Analysis", "Coding help"],
    pros: ["Great writing quality", "Often more careful", "Good at long documents"],
    cons: ["Still not perfect", "Tooling depends on where you use it"],
    pricing: { tier: "freemium", note: "Free tier + paid plans" },
    alternatives: [{ name: "ChatGPT", slug: "chatgpt" }, { name: "Gemini", slug: "gemini" }],
    tags: ["ai", "assistant", "writing"],
    rating: 4.4,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t20",
    slug: "gemini",
    name: "Gemini",
    oneLiner: "Best fit when you live in Google's ecosystem and want tight integration.",
    description:
      "Gemini is Google's AI assistant, strong in Google ecosystem workflows and multimodal tasks depending on the product surface.",
    useCases: ["Research", "Drafting", "Workspace help", "Multimodal tasks"],
    pros: ["Google integration", "Good for docs/workspace flows", "Multimodal support"],
    cons: ["Experience varies by surface", "Not always consistent across tasks"],
    pricing: { tier: "freemium", note: "Free tier + paid plans" },
    alternatives: [{ name: "ChatGPT", slug: "chatgpt" }, { name: "Claude", slug: "claude" }],
    tags: ["ai", "assistant", "productivity"],
    rating: 4.3,
    users: "Massive",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t21",
    slug: "playht",
    name: "PlayHT",
    oneLiner: "Text-to-speech with solid voice options for creators and devs.",
    description:
      "PlayHT is a text-to-speech platform for voiceovers and product TTS, with a range of voices and dev-friendly integrations. It's a practical alternative when you want good quality without over-optimizing for 'perfect acting'.",
    useCases: ["Voiceovers", "Narration", "App TTS", "Content dubbing", "Explainer videos"],
    pros: ["Good voice variety", "Useful APIs", "Decent creator workflow", "Practical for product TTS"],
    cons: ["Quality varies per voice", "Costs scale with usage", "Some voices can sound inconsistent across long reads"],
    pricing: {
      tier: "paid",
      note: "Paid plans (usage-based tiers)",
      details: "Pricing varies by plan and usage limits. Best to estimate from expected monthly characters/minutes.",
    },
    alternatives: [
      { name: "ElevenLabs", slug: "elevenlabs" },
      { name: "Azure TTS", slug: "azure-tts" },
      { name: "Resemble AI", slug: "resemble-ai" },
    ],
    tags: ["audio", "voice", "creator", "dev"],
    rating: 4.2,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t22",
    slug: "azure-tts",
    name: "Azure Text to Speech",
    oneLiner: "Enterprise-friendly TTS with predictable billing if you're already in Azure land.",
    description:
      "Azure Text to Speech (part of Azure AI Speech) is designed for production and enterprise use: stable APIs, predictable ops, and easy integration if your stack already uses Microsoft services.",
    useCases: ["Product TTS", "Enterprise apps", "Accessibility", "IVR/call flows", "Multilingual narration"],
    pros: ["Enterprise integration", "Stable platform", "Good docs", "Works well at scale"],
    cons: ["Less creator-friendly UX", "Can feel heavyweight for small projects", "Voice 'personality' may be less fun than creator-first tools"],
    pricing: {
      tier: "paid",
      note: "Usage-based (Azure billing)",
      details: "Pricing depends on usage volume and voice type. Best for teams already paying Azure bills.",
    },
    alternatives: [
      { name: "ElevenLabs", slug: "elevenlabs" },
      { name: "PlayHT", slug: "playht" },
      { name: "Google Cloud TTS", slug: "google-cloud-tts" },
    ],
    tags: ["audio", "voice", "dev", "enterprise"],
    rating: 4.1,
    users: "Enterprise",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t23",
    slug: "dalle",
    name: "DALL·E",
    oneLiner: "OpenAI's image generator for straightforward generation and editing.",
    description:
      "DALL·E creates images from text descriptions with a clean interface and clear licensing. Good for product images, illustrations, and quick visual concepts when you need reliability over cutting-edge aesthetics.",
    useCases: ["Product images", "Quick illustrations", "Concept visualization", "Image editing", "Marketing graphics"],
    pros: ["Straightforward interface", "Good editing features", "Clear licensing", "Reliable results"],
    cons: ["Less aesthetic consistency than Midjourney", "Credit costs add up", "Style options more limited"],
    pricing: { tier: "paid", note: "Credit-based pricing through OpenAI" },
    alternatives: [
      { name: "Midjourney", slug: "midjourney" },
      { name: "Stable Diffusion", slug: "stable-diffusion" },
      { name: "Leonardo", slug: "leonardo" },
    ],
    tags: ["image", "ai", "design"],
    rating: 4.3,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t24",
    slug: "stable-diffusion",
    name: "Stable Diffusion",
    oneLiner: "Open-source image generation for people who want total control and don't mind complexity.",
    description:
      "Stable Diffusion is an open-source image model you can run locally or via cloud services. Maximum customization and control, but requires technical comfort and prompt engineering skills.",
    useCases: ["Custom model training", "Local generation", "API integration", "Style customization", "High-volume generation"],
    pros: ["Full control", "Can run locally", "No per-image costs if self-hosted", "Extensive customization"],
    cons: ["Technical setup required", "Steep learning curve", "Quality depends heavily on prompts and settings"],
    pricing: { tier: "free", note: "Free open-source software (hosting/compute costs vary)" },
    alternatives: [
      { name: "Midjourney", slug: "midjourney" },
      { name: "DALL·E", slug: "dalle" },
      { name: "Leonardo", slug: "leonardo" },
    ],
    tags: ["image", "ai", "open-source"],
    rating: 4.4,
    users: "Technical",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t25",
    slug: "grammarly",
    name: "Grammarly",
    oneLiner: "Grammar and writing assistant that lives everywhere you write.",
    description:
      "Grammarly checks grammar, clarity, tone, and style across browsers, apps, and platforms. The all-rounder for professional writing quality without thinking about it.",
    useCases: ["Email writing", "Document editing", "Social media posts", "Professional communication", "Academic writing"],
    pros: ["Works everywhere", "Real-time checking", "Tone suggestions", "Consistent quality", "Team features available"],
    cons: ["Can be intrusive", "Premium cost for best features", "Sometimes overly prescriptive"],
    pricing: { tier: "freemium", note: "Free basic + Premium around $12/mo + Business plans" },
    alternatives: [
      { name: "QuillBot", slug: "quillbot" },
      { name: "Hemingway", slug: "hemingway" },
      { name: "ProWritingAid", slug: "prowritingaid" },
    ],
    tags: ["writing", "grammar", "productivity"],
    rating: 4.5,
    users: "Massive",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t26",
    slug: "quillbot",
    name: "QuillBot",
    oneLiner: "Paraphrasing and rewriting tool for when you need to say it differently.",
    description:
      "QuillBot specializes in paraphrasing, summarizing, and rewriting text. Popular with students and content creators who need to rework existing content.",
    useCases: ["Paraphrasing", "Summarization", "Research writing", "Content rewriting", "Grammar checking"],
    pros: ["Strong paraphrasing", "Multiple rewrite modes", "Good for academic work", "Plagiarism checker included"],
    cons: ["Can flatten voice and tone", "Premium required for full features", "Rewrites sometimes reduce quality"],
    pricing: { tier: "freemium", note: "Free basic + Premium around $20/mo" },
    alternatives: [
      { name: "Grammarly", slug: "grammarly" },
      { name: "Wordtune", slug: "wordtune" },
      { name: "Hemingway", slug: "hemingway" },
    ],
    tags: ["writing", "paraphrasing", "students"],
    rating: 4.1,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t27",
    slug: "hemingway",
    name: "Hemingway Editor",
    oneLiner: "Makes your writing bold and clear by highlighting everything that's not.",
    description:
      "Hemingway Editor focuses on readability by highlighting complex sentences, passive voice, and adverbs. Great for forcing clarity in technical docs or blog posts.",
    useCases: ["Simplifying text", "Technical writing", "Blog posts", "Clear communication", "Readability improvement"],
    pros: ["Forces clarity", "One-time purchase option", "Simple interface", "Instant readability score"],
    cons: ["No grammar checking", "Can be overly aggressive", "Doesn't understand when complexity is needed"],
    pricing: { tier: "freemium", note: "Free web version + $20 desktop one-time purchase" },
    alternatives: [
      { name: "Grammarly", slug: "grammarly" },
      { name: "ProWritingAid", slug: "prowritingaid" },
    ],
    tags: ["writing", "clarity", "editing"],
    rating: 4.3,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t28",
    slug: "zapier",
    name: "Zapier",
    oneLiner: "Connect apps and automate workflows without code (until the bill arrives).",
    description:
      "Zapier automates workflows between thousands of apps with a visual interface. Best for simple automations and when non-technical teams need to connect tools quickly.",
    useCases: ["Connect SaaS apps", "Automate data entry", "Trigger notifications", "Sync between tools", "Simple workflows"],
    pros: ["Huge integration library", "No-code interface", "Quick to set up", "Good for simple automations"],
    cons: ["Costs scale quickly", "Complex workflows get messy", "Can be less reliable than code", "Rate limits on cheaper plans"],
    pricing: { tier: "freemium", note: "Free tier + paid plans starting around $20/mo, scaling with tasks" },
    alternatives: [
      { name: "Make", slug: "make" },
      { name: "n8n", slug: "n8n" },
      { name: "Integromat", slug: "integromat" },
    ],
    tags: ["automation", "no-code", "productivity"],
    rating: 4.4,
    users: "Massive",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t29",
    slug: "make",
    name: "Make (formerly Integromat)",
    oneLiner: "Visual automation with more power than Zapier, slightly more brain-work required.",
    description:
      "Make provides visual workflow automation with more advanced features like branching, error handling, and iterations. Better for complex workflows when Zapier feels limiting.",
    useCases: ["Complex workflows", "Data transformation", "Multi-step automations", "Conditional logic", "API integrations"],
    pros: ["More powerful than Zapier", "Visual workflow builder", "Better for complex logic", "Generous free tier"],
    cons: ["Steeper learning curve", "Can over-complicate simple tasks", "Less popular than Zapier"],
    pricing: { tier: "freemium", note: "Free tier + paid plans with competitive pricing" },
    alternatives: [
      { name: "Zapier", slug: "zapier" },
      { name: "n8n", slug: "n8n" },
      { name: "Pipedream", slug: "pipedream" },
    ],
    tags: ["automation", "no-code", "workflow"],
    rating: 4.5,
    users: "Growing",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t30",
    slug: "n8n",
    name: "n8n",
    oneLiner: "Open-source automation for developers who want control and self-hosting.",
    description:
      "n8n is an open-source automation platform you can self-host or use in the cloud. Maximum control and customization but requires technical expertise to set up and maintain.",
    useCases: ["Self-hosted automation", "Custom integrations", "API workflows", "Complex business logic", "Data pipelines"],
    pros: ["Full control", "Self-hostable", "No task limits when self-hosted", "Extensible with code"],
    cons: ["Requires technical setup", "Infrastructure management needed", "Smaller community than competitors"],
    pricing: { tier: "freemium", note: "Free self-hosted + paid cloud plans" },
    alternatives: [
      { name: "Zapier", slug: "zapier" },
      { name: "Make", slug: "make" },
      { name: "Pipedream", slug: "pipedream" },
    ],
    tags: ["automation", "open-source", "dev"],
    rating: 4.6,
    users: "Technical",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t31",
    slug: "figma",
    name: "Figma",
    oneLiner: "Design tool that made everyone realize collaboration doesn't have to suck.",
    description:
      "Figma is a browser-based design tool with real-time collaboration, prototyping, and developer handoff. Industry standard for product design teams who value collaboration.",
    useCases: ["UI/UX design", "Prototyping", "Design systems", "Collaboration", "Developer handoff"],
    pros: ["Real-time collaboration", "Cross-platform", "Strong community", "Good developer handoff", "Plugin ecosystem"],
    cons: ["Can feel slower than native apps", "Requires internet", "Complex files can lag", "Adobe acquisition concerns"],
    pricing: { tier: "freemium", note: "Free for individuals + paid team plans starting around $15/user/mo" },
    alternatives: [
      { name: "Sketch", slug: "sketch" },
      { name: "Adobe XD", slug: "adobe-xd" },
      { name: "Penpot", slug: "penpot" },
    ],
    tags: ["design", "ui", "collaboration"],
    rating: 4.7,
    users: "Massive",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t32",
    slug: "sketch",
    name: "Sketch",
    oneLiner: "Mac-native design tool for teams who prioritize speed over cloud collaboration.",
    description:
      "Sketch is a Mac-only vector design tool with strong plugin ecosystem. Faster than browser-based tools but collaboration requires workarounds. Still popular with established design teams.",
    useCases: ["UI design", "Icon design", "Design systems", "Desktop app design", "Mac-centric workflows"],
    pros: ["Native Mac performance", "Mature plugin ecosystem", "Fast local work", "One-time license option"],
    cons: ["Mac only", "Collaboration less seamless than Figma", "Losing market share", "Cloud features cost extra"],
    pricing: { tier: "paid", note: "Subscription or one-time license, typically around $10/mo or $99 one-time" },
    alternatives: [
      { name: "Figma", slug: "figma" },
      { name: "Adobe XD", slug: "adobe-xd" },
      { name: "Affinity Designer", slug: "affinity-designer" },
    ],
    tags: ["design", "mac", "ui"],
    rating: 4.4,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t33",
    slug: "adobe-xd",
    name: "Adobe XD",
    oneLiner: "Adobe's design tool that's fine if you're already paying for Creative Cloud.",
    description:
      "Adobe XD is a design and prototyping tool bundled with Creative Cloud. Decent features but lags behind competitors in adoption and innovation. Main value is ecosystem integration.",
    useCases: ["UI design", "Prototyping", "Adobe ecosystem workflows", "Simple design projects"],
    pros: ["Included with Creative Cloud", "Good Adobe integration", "Clean interface", "Decent prototyping"],
    cons: ["Losing features and focus", "Smaller community", "Behind competitors", "Future unclear"],
    pricing: { tier: "freemium", note: "Free basic + included in Creative Cloud (~$55/mo)" },
    alternatives: [
      { name: "Figma", slug: "figma" },
      { name: "Sketch", slug: "sketch" },
      { name: "Framer", slug: "framer" },
    ],
    tags: ["design", "adobe", "ui"],
    rating: 3.9,
    users: "Declining",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t34",
    slug: "linear",
    name: "Linear",
    oneLiner: "Project management built for engineering velocity, not process bureaucracy.",
    description:
      "Linear is an issue tracker and project management tool designed for speed with keyboard shortcuts, clean design, and Git integration. Loved by engineering teams who hate Jira.",
    useCases: ["Issue tracking", "Sprint planning", "Roadmaps", "Bug tracking", "Engineering workflows"],
    pros: ["Very fast", "Keyboard-driven", "Clean interface", "Great Git integration", "Modern UX"],
    cons: ["Limited customization", "Best for pure engineering", "Expensive for large teams", "Less flexible than Jira"],
    pricing: { tier: "freemium", note: "Free for small teams + paid plans around $8/user/mo" },
    alternatives: [
      { name: "Jira", slug: "jira" },
      { name: "Height", slug: "height" },
      { name: "Plane", slug: "plane" },
    ],
    tags: ["project-management", "dev", "productivity"],
    rating: 4.8,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t35",
    slug: "jira",
    name: "Jira",
    oneLiner: "Enterprise project management that your company bought and your team tolerates.",
    description:
      "Jira is Atlassian's project management platform with maximum flexibility and enterprise features. Powerful but complex, requiring dedicated admins and often becoming bloated.",
    useCases: ["Enterprise project management", "Complex workflows", "Compliance tracking", "Cross-team coordination"],
    pros: ["Extremely flexible", "Enterprise features", "Huge ecosystem", "Good for complex organizations"],
    cons: ["Complex and slow", "Requires admin expertise", "Expensive at scale", "Often over-customized"],
    pricing: { tier: "freemium", note: "Free for small teams + paid plans starting around $8/user/mo, scaling up" },
    alternatives: [
      { name: "Linear", slug: "linear" },
      { name: "Asana", slug: "asana" },
      { name: "Monday", slug: "monday" },
    ],
    tags: ["project-management", "enterprise"],
    rating: 4.0,
    users: "Massive",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t36",
    slug: "asana",
    name: "Asana",
    oneLiner: "Project management that works for mixed teams doing more than just engineering.",
    description:
      "Asana is a flexible project management tool that bridges engineering and non-engineering work. Good for cross-functional teams who need coordination without Jira's complexity.",
    useCases: ["Cross-team projects", "Marketing campaigns", "Mixed workflows", "Task management", "Team coordination"],
    pros: ["Flexible for different work types", "Good collaboration features", "Multiple view options", "Integrations"],
    cons: ["Can feel cluttered", "Not optimized for pure engineering", "Gets expensive", "Learning curve for advanced features"],
    pricing: { tier: "freemium", note: "Free basic + paid plans starting around $11/user/mo" },
    alternatives: [
      { name: "Monday", slug: "monday" },
      { name: "Click Up", slug: "clickup" },
      { name: "Jira", slug: "jira" },
    ],
    tags: ["project-management", "collaboration"],
    rating: 4.3,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t37",
    slug: "webflow",
    name: "Webflow",
    oneLiner: "Build production websites with design freedom, no code required (mostly).",
    description:
      "Webflow is a visual website builder that generates clean code. Powerful for designers who want control without coding, though CMS and interactions require learning the Webflow way.",
    useCases: ["Marketing sites", "Portfolio sites", "Landing pages", "Content sites", "Client projects"],
    pros: ["Full design control", "Clean code output", "Powerful CMS", "No code required", "Good SEO"],
    cons: ["Learning curve", "Traffic-based pricing can surprise", "Lock-in concerns", "Complex for simple sites"],
    pricing: { tier: "freemium", note: "Free basic + site plans starting $14/mo + CMS plans higher" },
    alternatives: [
      { name: "Framer", slug: "framer" },
      { name: "WordPress", slug: "wordpress" },
      { name: "Squarespace", slug: "squarespace" },
    ],
    tags: ["website", "no-code", "design"],
    rating: 4.5,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t38",
    slug: "wordpress",
    name: "WordPress",
    oneLiner: "The old reliable that powers more of the web than you'd expect.",
    description:
      "WordPress is an open-source CMS powering over 40% of websites. Maximum flexibility and ecosystem but requires hosting management and plugin maintenance. Still relevant despite newer alternatives.",
    useCases: ["Blogs", "Content sites", "E-commerce", "Business sites", "Custom web applications"],
    pros: ["Huge ecosystem", "Maximum flexibility", "Open source", "Mature platform", "Endless plugins"],
    cons: ["Security maintenance required", "Plugin conflicts", "Performance varies", "Can feel dated", "Hosting complexity"],
    pricing: { tier: "free", note: "Free software + hosting/theme/plugin costs vary widely" },
    alternatives: [
      { name: "Webflow", slug: "webflow" },
      { name: "Ghost", slug: "ghost" },
      { name: "Shopify", slug: "shopify" },
    ],
    tags: ["cms", "website", "blogging"],
    rating: 4.2,
    users: "Massive",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t39",
    slug: "stripe",
    name: "Stripe",
    oneLiner: "Payment processing for developers who want control and clean APIs.",
    description:
      "Stripe provides payment APIs and infrastructure for online businesses. Developer-friendly with extensive features for subscriptions, fraud prevention, and global payments.",
    useCases: ["Online payments", "Subscription billing", "Marketplace payments", "Invoicing", "Revenue optimization"],
    pros: ["Excellent APIs", "Strong documentation", "Flexible features", "Global support", "Good developer experience"],
    cons: ["Requires technical integration", "Fees add up at scale", "Complexity for simple needs", "Support can be slow"],
    pricing: { tier: "paid", note: "2.9% + $0.30 per transaction + subscription fees" },
    alternatives: [
      { name: "PayPal", slug: "paypal" },
      { name: "Square", slug: "square" },
      { name: "Paddle", slug: "paddle" },
    ],
    tags: ["payments", "e-commerce", "dev"],
    rating: 4.6,
    users: "Massive",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t40",
    slug: "paypal",
    name: "PayPal",
    oneLiner: "Payment processing with instant buyer trust but merchant headaches.",
    description:
      "PayPal is a payment platform with strong brand recognition and buyer protection. Easy to integrate but fees are higher and customer experience can hurt conversion.",
    useCases: ["E-commerce checkout", "Invoicing", "International payments", "Peer-to-peer transfers"],
    pros: ["Brand trust", "Easy integration", "Buyer protection", "Multiple payment methods", "Global reach"],
    cons: ["Higher fees", "Account holds common", "Customer support issues", "Checkout UX can hurt conversion"],
    pricing: { tier: "paid", note: "2.9% + $0.30 domestic, higher for international" },
    alternatives: [
      { name: "Stripe", slug: "stripe" },
      { name: "Square", slug: "square" },
      { name: "Braintree", slug: "braintree" },
    ],
    tags: ["payments", "e-commerce"],
    rating: 4.0,
    users: "Massive",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t41",
    slug: "square",
    name: "Square",
    oneLiner: "Payment processing that actually works for retail and online together.",
    description:
      "Square provides unified payment processing for in-person and online sales with POS hardware and software. Best for retail businesses wanting consistent experience across channels.",
    useCases: ["Retail payments", "Restaurant POS", "Online store", "Invoicing", "Appointments"],
    pros: ["Unified in-person and online", "Easy hardware", "Good for retail", "Simple pricing", "Quick setup"],
    cons: ["Less flexible for complex online needs", "Account stability issues reported", "Limited customization"],
    pricing: { tier: "paid", note: "2.9% + $0.30 online, 2.6% + $0.10 in-person" },
    alternatives: [
      { name: "Stripe", slug: "stripe" },
      { name: "Clover", slug: "clover" },
      { name: "PayPal", slug: "paypal" },
    ],
    tags: ["payments", "pos", "retail"],
    rating: 4.4,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t42",
    slug: "notion",
    name: "Notion",
    oneLiner: "All-in-one workspace that's either perfect or completely overwhelming.",
    description:
      "Notion combines notes, databases, wikis, and project management in one flexible workspace. Powerful but can become over-engineered if you're not careful.",
    useCases: ["Team wikis", "Project management", "Note-taking", "Documentation", "Knowledge base"],
    pros: ["Very flexible", "Good collaboration", "Databases are powerful", "Template ecosystem", "Clean interface"],
    cons: ["Can get complex", "Offline support limited", "Performance issues with large workspaces", "Lock-in concerns"],
    pricing: { tier: "freemium", note: "Free personal + paid team plans starting $8/user/mo" },
    alternatives: [
      { name: "Obsidian", slug: "obsidian" },
      { name: "Coda", slug: "coda" },
      { name: "Confluence", slug: "confluence" },
    ],
    tags: ["notes", "productivity", "collaboration"],
    rating: 4.5,
    users: "Massive",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t43",
    slug: "loom",
    name: "Loom",
    oneLiner: "Screen recording that actually feels lighter than writing an email.",
    description:
      "Loom records quick screen and camera videos for async communication. Popular for bug reports, demos, feedback, and team updates when video is faster than writing.",
    useCases: ["Bug reports", "Product demos", "Team updates", "Code reviews", "Customer support"],
    pros: ["Very quick recording", "Good sharing", "Transcription included", "Comment threading", "Integrations"],
    cons: ["Free tier limits", "Video quality not cinema-grade", "Editing features basic", "Costs add up for teams"],
    pricing: { tier: "freemium", note: "Free basic (25 videos) + paid plans starting $12.50/user/mo" },
    alternatives: [
      { name: "Tango", slug: "tango" },
      { name: "Screen Studio", slug: "screen-studio" },
      { name: "OBS", slug: "obs" },
    ],
    tags: ["video", "communication", "productivity"],
    rating: 4.6,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t44",
    slug: "vercel",
    name: "Vercel",
    oneLiner: "Deploy frontend projects with zero config and actually good DX.",
    description:
      "Vercel is a deployment platform optimized for frontend frameworks, especially Next.js. Git-based deployment, preview environments, and edge functions with excellent developer experience.",
    useCases: ["Frontend deployment", "Next.js hosting", "Preview environments", "Edge functions", "Static sites"],
    pros: ["Excellent DX", "Fast deployments", "Preview deployments", "Edge network", "Zero config for Next.js"],
    cons: ["Can get expensive", "Vendor lock-in concerns", "Less flexible than raw cloud", "Bandwidth costs"],
    pricing: { tier: "freemium", note: "Free hobby + paid pro/team plans with usage pricing" },
    alternatives: [
      { name: "Netlify", slug: "netlify" },
      { name: "Cloudflare Pages", slug: "cloudflare-pages" },
      { name: "AWS Amplify", slug: "aws-amplify" },
    ],
    tags: ["deployment", "frontend", "dev"],
    rating: 4.7,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t45",
    slug: "supabase",
    name: "Supabase",
    oneLiner: "Open-source Firebase alternative that doesn't try to own your entire backend.",
    description:
      "Supabase provides PostgreSQL database, authentication, storage, and realtime subscriptions with open-source foundation. Firebase alternative without the lock-in.",
    useCases: ["App backend", "Authentication", "Real-time apps", "File storage", "PostgreSQL hosting"],
    pros: ["Open source", "Real PostgreSQL", "Good DX", "Generous free tier", "Less lock-in than Firebase"],
    cons: ["Newer platform", "Smaller ecosystem", "Some features still maturing", "Self-hosting complexity"],
    pricing: { tier: "freemium", note: "Free tier + paid plans starting $25/project/mo" },
    alternatives: [
      { name: "Firebase", slug: "firebase" },
      { name: "PlanetScale", slug: "planetscale" },
      { name: "Railway", slug: "railway" },
    ],
    tags: ["backend", "database", "dev"],
    rating: 4.6,
    users: "Growing",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t46",
    slug: "tailwind",
    name: "Tailwind CSS",
    oneLiner: "Utility-first CSS that makes styling fast once you accept it's not actual CSS.",
    description:
      "Tailwind CSS is a utility-first CSS framework where you compose styles with classes. Controversial but popular for fast styling without leaving HTML.",
    useCases: ["Rapid prototyping", "Component styling", "Responsive design", "Design systems", "Production sites"],
    pros: ["Very fast styling", "Consistent design tokens", "Good for components", "Great documentation", "Active community"],
    cons: ["HTML gets verbose", "Learning curve", "Build step required", "Purging needed for production"],
    pricing: { tier: "free", note: "Free open-source + paid Tailwind UI components" },
    alternatives: [
      { name: "Bootstrap", slug: "bootstrap" },
      { name: "CSS Modules", slug: "css-modules" },
      { name: "Styled Components", slug: "styled-components" },
    ],
    tags: ["css", "frontend", "dev"],
    rating: 4.7,
    users: "Massive",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t47",
    slug: "posthog",
    name: "PostHog",
    oneLiner: "Product analytics, feature flags, and experiments without stitching five tools.",
    description:
      "PostHog combines analytics, feature flags, session replay, and experiments in one platform. Open-source alternative to Amplitude + LaunchDarkly + FullStory combined.",
    useCases: ["Product analytics", "Feature flags", "A/B testing", "Session replay", "User behavior tracking"],
    pros: ["All-in-one platform", "Open source", "Self-hosting option", "Good for startups", "Transparent pricing"],
    cons: ["Less mature than specialized tools", "Can be expensive at scale", "Some features still developing"],
    pricing: { tier: "freemium", note: "Free tier + usage-based pricing starting free" },
    alternatives: [
      { name: "Amplitude", slug: "amplitude" },
      { name: "Mixpanel", slug: "mixpanel" },
      { name: "Heap", slug: "heap" },
    ],
    tags: ["analytics", "product", "dev"],
    rating: 4.5,
    users: "Growing",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t48",
    slug: "resend",
    name: "Resend",
    oneLiner: "Transactional email for developers who are tired of SendGrid's complexity.",
    description:
      "Resend is a modern transactional email API focused on developer experience. Clean API, React email templates, and good deliverability without enterprise complexity.",
    useCases: ["Transactional emails", "Product notifications", "Welcome emails", "Password resets", "Receipts"],
    pros: ["Great DX", "React email templates", "Clean API", "Good deliverability", "Reasonable pricing"],
    cons: ["Newer platform", "Limited marketing features", "Smaller ecosystem", "Less proven at massive scale"],
    pricing: { tier: "freemium", note: "Free tier (100 emails/day) + paid plans starting $20/mo" },
    alternatives: [
      { name: "SendGrid", slug: "sendgrid" },
      { name: "Postmark", slug: "postmark" },
      { name: "AWS SES", slug: "aws-ses" },
    ],
    tags: ["email", "dev", "transactional"],
    rating: 4.6,
    users: "Growing",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t49",
    slug: "cal-com",
    name: "Cal.com",
    oneLiner: "Open-source Calendly that you can self-host and actually customize.",
    description:
      "Cal.com is an open-source scheduling platform with branded booking pages, team features, and integrations. Calendly alternative without the pricing surprises.",
    useCases: ["Meeting scheduling", "Team scheduling", "Booking pages", "Calendar management", "Availability"],
    pros: ["Open source", "Self-hosting option", "No per-seat pricing", "Good customization", "Active development"],
    cons: ["Newer than Calendly", "Some features less polished", "Self-hosting requires setup"],
    pricing: { tier: "freemium", note: "Free self-hosted + paid cloud starting $12/user/mo" },
    alternatives: [
      { name: "Calendly", slug: "calendly" },
      { name: "SavvyCal", slug: "savvycal" },
      { name: "YouCanBookMe", slug: "youbookme" },
    ],
    tags: ["scheduling", "productivity", "open-source"],
    rating: 4.4,
    users: "Growing",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t50",
    slug: "descript",
    name: "Descript",
    oneLiner: "Edit podcasts and videos by editing text, like magic but real.",
    description:
      "Descript lets you edit audio and video by editing transcription text. Game-changing for podcasters and video creators who want editing to feel less tedious.",
    useCases: ["Podcast editing", "Video editing", "Transcription", "Screen recording", "Content repurposing"],
    pros: ["Text-based editing", "Filler word removal", "Studio-quality voices", "Screen recording built-in", "Fast workflow"],
    cons: ["Export quality has limits", "Learning curve for traditional editors", "Subscription required for best features"],
    pricing: { tier: "freemium", note: "Free basic + paid plans starting $12/user/mo" },
    alternatives: [
      { name: "Adobe Premiere", slug: "premiere" },
      { name: "Final Cut Pro", slug: "final-cut" },
      { name: "Riverside", slug: "riverside" },
    ],
    tags: ["video", "audio", "editing", "creator"],
    rating: 4.6,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },
];
