// lib/content/tools.ts
import type { Tool } from "@/lib/data-types";

export const tools: Tool[] = [
  {
    id: "t1",
    slug: "cursor",
    name: "Cursor",
    oneLiner: "AI-first editor that makes refactors feel less like punishment.",
    description:
      "Cursor is a code editor built around AI workflows (multi-file edits, codebase-wide context, and agent-style changes). It shines when you want to ship faster, but still need reviewable diffs.",
    useCases: [
      "Refactor across multiple files",
      "Generate scaffolds safely",
      "Navigate large codebases",
      "Draft tests and small utilities",
    ],
    pros: [
      "Strong codebase-context UX",
      "Fast iteration loop",
      "Great diff/patch workflow",
      "Multi-file editing and agent flows",
    ],
    cons: [
      "Still makes confident mistakes",
      "Can encourage sloppy review habits",
      "Paid tiers can add up if you live in it",
    ],
    pricing: {
      tier: "freemium",
      note: "Free Hobby tier + paid tiers (Pro and above)",
      details: "Pro is commonly listed at $20/mo; higher tiers expand limits and context windows.",
    },
    alternatives: [
      { name: "VS Code + Copilot", slug: "vscode-copilot" },
      { name: "JetBrains AI", slug: "jetbrains-ai" },
      { name: "Windsurf", slug: "windsurf" },
    ],
    tags: ["dev", "coding", "editor", "ai-native"],
    rating: 4.6,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t2",
    slug: "perplexity",
    name: "Perplexity",
    oneLiner: "Search + answers that can cite sources when you force it to behave.",
    description:
      "Perplexity is an answer-first search experience that can cite sources and help you explore a topic quickly. Best used as a launchpad, not a replacement for reading.",
    useCases: ["Research fast", "Compare viewpoints", "Find starting sources", "Summarize articles"],
    pros: ["Fast discovery", "Useful summaries", "Good for brainstorming queries", "Often includes citations"],
    cons: ["Citations can be uneven", "Still requires verification", "Paid tier cost may not be worth it for casual use"],
    pricing: { tier: "freemium", note: "Free tier + paid plans", details: "Paid plans add higher limits and model access." },
    alternatives: [
      { name: "Kagi", slug: "kagi" },
      { name: "Google", slug: "google" },
      { name: "Bing", slug: "bing" },
    ],
    tags: ["search", "research", "productivity"],
    rating: 4.3,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t3",
    slug: "notion-ai",
    name: "Notion AI",
    oneLiner: "Draft, summarize, and clean up docs without leaving your workspace.",
    description:
      "Notion AI adds drafting, summarization, and writing help inside Notion. Best when your notes, tasks, and docs already live there.",
    useCases: ["Summarize notes", "Draft docs", "Rewrite text", "Meeting summaries", "Turn notes into action items"],
    pros: ["Zero context switching", "Good for drafting", "Team-friendly", "Works inside docs/databases"],
    cons: ["Outputs can be generic", "Not the best for deep technical accuracy", "Pricing/availability varies by plan"],
    pricing: { tier: "paid", note: "Notion plans (AI availability varies by plan/workspace)" },
    alternatives: [
      { name: "Google Docs AI", slug: "google-docs-ai" },
      { name: "Craft", slug: "craft" },
      { name: "Coda", slug: "coda" },
    ],
    tags: ["writing", "notes", "team", "productivity"],
    rating: 4.0,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t4",
    slug: "elevenlabs",
    name: "ElevenLabs",
    oneLiner: "Voice generation for creators, narration, and apps (use responsibly).",
    description:
      "ElevenLabs is a leading AI voice platform for voiceovers, dubbing, and character voices, with strong quality and creator-focused workflows.",
    useCases: ["Voiceovers", "Dubbing", "Character voices", "Audiobook narration", "Podcast intros"],
    pros: ["High quality voices", "Good language coverage", "Creator-friendly UX", "Strong tooling ecosystem"],
    cons: ["Costs scale with usage", "Ethics/legal risk if abused", "Quality varies by language/accent"],
    pricing: { tier: "freemium", note: "Free tier + paid plans", details: "Plans differ by usage/limits; check official tiers." },
    alternatives: [
      { name: "PlayHT", slug: "playht" },
      { name: "Azure TTS", slug: "azure-tts" },
      { name: "Resemble AI", slug: "resemble-ai" },
    ],
    tags: ["audio", "voice", "creator", "content"],
    rating: 4.6,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t5",
    slug: "runpod",
    name: "RunPod",
    oneLiner: "Rent GPUs without selling a kidney. Useful for ML experiments.",
    description:
      "RunPod is a cloud GPU platform for ML training and inference. Good for bursty workloads and experiments when you don’t want long-term commitments.",
    useCases: ["GPU notebooks", "Model inference", "Training bursts", "Fine-tuning models", "Serverless inference"],
    pros: ["Fast GPU access", "Flexible pricing model", "Good for experiments", "Templates and tooling"],
    cons: ["Costs can spike fast", "You still need DevOps competence", "Availability varies by region/GPU"],
    pricing: { tier: "paid", note: "Usage-based GPU pricing", details: "Costs vary heavily by GPU type and region." },
    alternatives: [
      { name: "Vast.ai", slug: "vast-ai" },
      { name: "Lambda", slug: "lambda" },
      { name: "Paperspace", slug: "paperspace" },
    ],
    tags: ["gpu", "ml", "infra", "cloud"],
    rating: 4.4,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t6",
    slug: "langfuse",
    name: "Langfuse",
    oneLiner: "LLM observability: traces, evals, and why your agent went rogue.",
    description:
      "Langfuse is an open-source LLM engineering platform: tracing, prompt management, evaluations, and monitoring for AI apps and agents.",
    useCases: ["Trace LLM calls", "Evaluate outputs", "Debug agents", "Monitor costs", "A/B test prompts"],
    pros: ["Great visibility", "Self-hostable option", "Team workflows", "Makes issues reproducible"],
    cons: ["Setup overhead", "Evals still require good design", "Learning curve for teams new to observability"],
    pricing: { tier: "freemium", note: "Free tier + paid cloud; self-host option", details: "Cloud pricing is usage-based with base plan tiers." },
    alternatives: [
      { name: "LangSmith", slug: "langsmith" },
      { name: "Helicone", slug: "helicone" },
      { name: "W&B Weave", slug: "wandb-weave" },
    ],
    tags: ["llm", "observability", "agents", "dev"],
    rating: 4.5,
    users: "Growing",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t7",
    slug: "zotero",
    name: "Zotero",
    oneLiner: "Reference manager for research that doesn't hate you back.",
    description:
      "Zotero is a free, open-source reference manager for papers, citations, and bibliographies. A staple for students and researchers.",
    useCases: ["Manage citations", "Organize papers", "Collaborate on reading lists", "Generate bibliographies"],
    pros: ["Free and reliable", "Works offline", "Great citation support", "Browser extension"],
    cons: ["Free sync storage is limited", "UI feels academic", "Mobile experience is okay, not amazing"],
    pricing: { tier: "freemium", note: "Free app + paid sync storage plans" },
    alternatives: [
      { name: "Mendeley", slug: "mendeley" },
      { name: "Paperpile", slug: "paperpile" },
      { name: "EndNote", slug: "endnote" },
    ],
    tags: ["research", "citations", "writing", "academic"],
    rating: 4.3,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t8",
    slug: "excalidraw",
    name: "Excalidraw",
    oneLiner: "Sketch diagrams that look handmade, not corporate.",
    description:
      "Excalidraw is a virtual whiteboard for quick, hand-drawn style diagrams. Perfect for docs, systems thinking, and explaining ideas fast.",
    useCases: ["System diagrams", "Quick wireframes", "Explain ideas visually", "Architecture planning"],
    pros: ["Fast", "Shareable", "Low friction", "Collaboration", "Great for docs"],
    cons: ["Not for pixel-perfect design", "Huge boards can get messy", "Limited styling options"],
    pricing: { tier: "freemium", note: "Free core + team features available" },
    alternatives: [
      { name: "FigJam", slug: "figjam" },
      { name: "Miro", slug: "miro" },
      { name: "tldraw", slug: "tldraw" },
    ],
    tags: ["diagrams", "design", "productivity", "collaboration"],
    rating: 4.7,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t9",
    slug: "obsidian",
    name: "Obsidian",
    oneLiner: "Local-first knowledge base for people who hoard ideas.",
    description:
      "Obsidian is a local-first knowledge base on Markdown files with powerful linking and plugins. Great for building a personal wiki or study system.",
    useCases: ["Second brain", "Study notes", "Personal wiki", "Daily journaling", "Knowledge management"],
    pros: ["Offline-first", "Plugin ecosystem", "Fast search", "Markdown files", "Flexible organization"],
    cons: ["Can become a hobby", "Sync is paid", "Steep learning curve if you over-customize"],
    pricing: { tier: "freemium", note: "Free app + paid Sync/Publish add-ons", details: "Sync is commonly listed around $4–$5/mo depending on billing." },
    alternatives: [
      { name: "Notion", slug: "notion" },
      { name: "Logseq", slug: "logseq" },
      { name: "Roam Research", slug: "roam" },
    ],
    tags: ["notes", "productivity", "knowledge", "pkm"],
    rating: 4.8,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t10",
    slug: "framer",
    name: "Framer",
    oneLiner: "Ship landing pages fast with animations that don’t look tragic.",
    description:
      "Framer is a design-to-site builder with strong interactions, templates, and CMS. Great for marketing pages and quick launches without writing code.",
    useCases: ["Landing pages", "Marketing sites", "Portfolios", "Prototypes", "Content sites"],
    pros: ["Fast publishing", "Good templates", "Smooth interactions", "Built-in CMS", "Strong SEO basics"],
    cons: ["Can get pricey as you scale", "Less flexible than custom code", "Complex interactions have a learning curve"],
    pricing: { tier: "freemium", note: "Free plan + paid upgrades for custom domains and higher limits" },
    alternatives: [
      { name: "Webflow", slug: "webflow" },
      { name: "Carrd", slug: "carrd" },
      { name: "Typedream", slug: "typedream" },
    ],
    tags: ["design", "marketing", "website", "no-code"],
    rating: 4.6,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t11",
    slug: "midjourney",
    name: "Midjourney",
    oneLiner: "Generate images that make people ask ‘wait, that’s AI?’",
    description:
      "Midjourney is a top-tier image generator known for strong aesthetics and style. It’s popular for concept art and marketing visuals.",
    useCases: ["Concept art", "Marketing visuals", "Creative exploration", "Mood boards"],
    pros: ["High aesthetic quality", "Strong style results", "Large community", "Regular improvements"],
    cons: ["Workflow can be awkward (Discord)", "No real free tier", "Not ideal for precise edits"],
    pricing: { tier: "paid", note: "Subscription-based" },
    alternatives: [
      { name: "DALL·E", slug: "dalle" },
      { name: "Stable Diffusion", slug: "stable-diffusion" },
      { name: "Leonardo", slug: "leonardo" },
    ],
    tags: ["image", "ai", "design", "creator"],
    rating: 4.5,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t12",
    slug: "raycast",
    name: "Raycast",
    oneLiner: "Launcher that makes your Mac feel like it has superpowers.",
    description:
      "Raycast is a macOS launcher with extensions, clipboard history, snippets, automation, and optional AI features. Big time-saver if you live on keyboard shortcuts.",
    useCases: ["Quick actions", "Clipboard manager", "Window/workflow actions", "Run scripts", "Search apps/files fast"],
    pros: ["Very fast", "Great extensions", "Polished UX", "Keyboard-first workflow"],
    cons: ["macOS only", "Can be overwhelming at first", "Some features are paid"],
    pricing: { tier: "freemium", note: "Free core + paid upgrade for advanced features" },
    alternatives: [
      { name: "Alfred", slug: "alfred" },
      { name: "Spotlight", slug: "spotlight" },
    ],
    tags: ["productivity", "mac", "launcher", "tools"],
    rating: 4.9,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  // ----------------------------
  // Added tools (to support collections + comparisons + SEO breadth)
  // ----------------------------

  {
    id: "t13",
    slug: "kagi",
    name: "Kagi",
    oneLiner: "Paid search for people who hate ads and love control.",
    description:
      "Kagi is a premium search engine focused on clean results, customization, and removing spam. Great if Google results feel like a landfill.",
    useCases: ["High-signal search", "Research", "Cleaner results", "Power-user search workflows"],
    pros: ["Less spam/SEO sludge", "Strong controls and filters", "Good for deep research"],
    cons: ["Paid", "Not everyone needs it", "Results can vary by region/topic"],
    pricing: { tier: "paid", note: "Subscription-based" },
    alternatives: [{ name: "Google", slug: "google" }, { name: "Perplexity", slug: "perplexity" }],
    tags: ["search", "research", "productivity"],
    rating: 4.4,
    users: "Niche",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t14",
    slug: "google",
    name: "Google Search",
    oneLiner: "The necessary mess. Best for breadth, worst for peace.",
    description:
      "Still the widest index for the open web. Great when you need coverage, but you’ll do more filtering yourself.",
    useCases: ["Broad research", "Finding official sources", "Local info", "Long-tail queries"],
    pros: ["Unmatched breadth", "Lots of niche results", "Strong for navigational searches"],
    cons: ["Ads and SEO spam", "More effort to filter", "Results can be inconsistent"],
    pricing: { tier: "free", note: "Free" },
    alternatives: [{ name: "Kagi", slug: "kagi" }, { name: "Bing", slug: "bing" }],
    tags: ["search", "research"],
    rating: 4.1,
    users: "Everyone",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t15",
    slug: "vscode-copilot",
    name: "VS Code + GitHub Copilot",
    oneLiner: "Most flexible dev setup, if you don’t install 47 extensions you’ll regret.",
    description:
      "VS Code with Copilot gives strong inline suggestions and chat assistance while keeping you in the most popular editor ecosystem.",
    useCases: ["Autocomplete", "Small refactors", "Boilerplate generation", "Quick explanations"],
    pros: ["Huge extension ecosystem", "Familiar workflow", "Good code suggestions"],
    cons: ["Context can be weaker than AI-native editors", "Setup drift between machines/teams"],
    pricing: { tier: "paid", note: "Copilot is paid; VS Code is free" },
    alternatives: [{ name: "Cursor", slug: "cursor" }, { name: "JetBrains AI", slug: "jetbrains-ai" }],
    tags: ["dev", "coding", "editor"],
    rating: 4.4,
    users: "Massive",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t16",
    slug: "jetbrains-ai",
    name: "JetBrains AI",
    oneLiner: "Convenient AI inside IntelliJ/WebStorm for people already deep in JetBrains.",
    description:
      "JetBrains AI integrates into JetBrains IDEs for code generation, explanation, and assistance without switching tools.",
    useCases: ["Refactors in JetBrains", "Code understanding", "Inline suggestions", "IDE-native workflows"],
    pros: ["Fits JetBrains workflow", "Strong IDE features + AI", "Good for large projects"],
    cons: ["Best value only if you already use JetBrains", "Not always the fastest for quick edits"],
    pricing: { tier: "paid", note: "Paid add-on / plan-based (varies by IDE/license)" },
    alternatives: [{ name: "Cursor", slug: "cursor" }, { name: "VS Code + Copilot", slug: "vscode-copilot" }],
    tags: ["dev", "coding", "editor"],
    rating: 4.2,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t17",
    slug: "windsurf",
    name: "Windsurf",
    oneLiner: "Another AI-native coding environment competing for your attention span.",
    description:
      "Windsurf is part of the new wave of AI-first coding tools. It’s aimed at faster multi-file edits and agent-style workflows.",
    useCases: ["Agentic coding", "Multi-file changes", "Repo exploration", "Rapid prototyping"],
    pros: ["AI-native workflow", "Good for fast iterations"],
    cons: ["Tooling is evolving fast", "You still need careful reviews"],
    pricing: { tier: "freemium", note: "Plans vary" },
    alternatives: [{ name: "Cursor", slug: "cursor" }, { name: "VS Code + Copilot", slug: "vscode-copilot" }],
    tags: ["dev", "coding", "ai-native"],
    rating: 4.1,
    users: "Growing",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t18",
    slug: "chatgpt",
    name: "ChatGPT",
    oneLiner: "General-purpose AI assistant for writing, coding, planning, and fixing your chaos.",
    description:
      "ChatGPT is a general AI assistant that can help with coding, writing, reasoning, and structured outputs. Best when you give clear constraints.",
    useCases: ["Drafting", "Debugging", "Planning", "Learning", "Structured output generation"],
    pros: ["Very flexible", "Good tool support in some environments", "Strong for structured prompts"],
    cons: ["Needs good prompts", "Can be confidently wrong", "Varies by model/settings"],
    pricing: { tier: "freemium", note: "Free tier + paid plans" },
    alternatives: [{ name: "Claude", slug: "claude" }, { name: "Gemini", slug: "gemini" }],
    tags: ["ai", "assistant", "productivity"],
    rating: 4.5,
    users: "Massive",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t19",
    slug: "claude",
    name: "Claude",
    oneLiner: "Strong writing + careful reasoning, especially when you want fewer hallucinations.",
    description:
      "Claude is an AI assistant often praised for clean writing and more cautious responses. Great for editing, analysis, and long-form drafting.",
    useCases: ["Writing and editing", "Summarization", "Analysis", "Coding help"],
    pros: ["Great writing quality", "Often more careful", "Good at long documents"],
    cons: ["Still not perfect", "Tooling depends on where you use it"],
    pricing: { tier: "freemium", note: "Free tier + paid plans" },
    alternatives: [{ name: "ChatGPT", slug: "chatgpt" }, { name: "Gemini", slug: "gemini" }],
    tags: ["ai", "assistant", "writing"],
    rating: 4.4,
    users: "Popular",
    updatedAtISO: "2026-01-24",
  },

  {
    id: "t20",
    slug: "gemini",
    name: "Gemini",
    oneLiner: "Best fit when you live in Google’s ecosystem and want tight integration.",
    description:
      "Gemini is Google’s AI assistant, strong in Google ecosystem workflows and multimodal tasks depending on the product surface.",
    useCases: ["Research", "Drafting", "Workspace help", "Multimodal tasks"],
    pros: ["Google integration", "Good for docs/workspace flows", "Multimodal support"],
    cons: ["Experience varies by surface", "Not always consistent across tasks"],
    pricing: { tier: "freemium", note: "Free tier + paid plans" },
    alternatives: [{ name: "ChatGPT", slug: "chatgpt" }, { name: "Claude", slug: "claude" }],
    tags: ["ai", "assistant", "productivity"],
    rating: 4.3,
    users: "Massive",
    updatedAtISO: "2026-01-24",
  },
{
  id: "t21",
  slug: "playht",
  name: "PlayHT",
  oneLiner: "Text-to-speech with solid voice options for creators and devs.",
  description:
    "PlayHT is a text-to-speech platform for voiceovers and product TTS, with a range of voices and dev-friendly integrations. It’s a practical alternative when you want good quality without over-optimizing for ‘perfect acting’.",
  useCases: ["Voiceovers", "Narration", "App TTS", "Content dubbing", "Explainer videos"],
  pros: ["Good voice variety", "Useful APIs", "Decent creator workflow", "Practical for product TTS"],
  cons: ["Quality varies per voice", "Costs scale with usage", "Some voices can sound inconsistent across long reads"],
  pricing: {
    tier: "paid",
    note: "Paid plans (usage-based tiers)",
    details: "Pricing varies by plan and usage limits. Best to estimate from expected monthly characters/minutes.",
  },
  alternatives: [
    { name: "ElevenLabs", slug: "elevenlabs" },
    { name: "Azure TTS", slug: "azure-tts" },
    { name: "Resemble AI", slug: "resemble-ai" },
  ],
  tags: ["audio", "voice", "creator", "dev"],
  rating: 4.2,
  users: "Popular",
  updatedAtISO: "2026-01-24",
},

{
  id: "t22",
  slug: "azure-tts",
  name: "Azure Text to Speech",
  oneLiner: "Enterprise-friendly TTS with predictable billing if you’re already in Azure land.",
  description:
    "Azure Text to Speech (part of Azure AI Speech) is designed for production and enterprise use: stable APIs, predictable ops, and easy integration if your stack already uses Microsoft services.",
  useCases: ["Product TTS", "Enterprise apps", "Accessibility", "IVR/call flows", "Multilingual narration"],
  pros: ["Enterprise integration", "Stable platform", "Good docs", "Works well at scale"],
  cons: ["Less creator-friendly UX", "Can feel heavyweight for small projects", "Voice ‘personality’ may be less fun than creator-first tools"],
  pricing: {
    tier: "paid",
    note: "Usage-based (Azure billing)",
    details: "Pricing depends on usage volume and voice type. Best for teams already paying Azure bills.",
  },
  alternatives: [
    { name: "ElevenLabs", slug: "elevenlabs" },
    { name: "PlayHT", slug: "playht" },
    { name: "Google Cloud TTS", slug: "google-cloud-tts" },
  ],
  tags: ["audio", "voice", "dev", "enterprise"],
  rating: 4.1,
  users: "Enterprise",
  updatedAtISO: "2026-01-24",
},
  
];