// lib/content/updates.ts
import type { ModelUpdate } from "@/lib/data-types";

export const updates: ModelUpdate[] = [
  {
    id: "u1",
    slug: "prompt-structure-winning",
    model: "Prompting",
    headline: "Structured prompts outperform vibes (again).",
    whatChanged: ["Checklists and constraints lead to more reliable outputs", "Long rambling prompts increase confusion and drift"],
    whoItAffects: ["Everyone who ‘just types thoughts’ into chat", "People building agent workflows"],
    whatToDoNow: ["Move constraints to the top", "Use headings + numbered requirements", "Ask for output format explicitly"],
    tldr: "Structure beats storytelling when you want consistent results.",
    tags: ["prompts", "workflow"],
    updatedAtISO: "2026-01-21",
  },
  {
    id: "u2",
    slug: "image-consistency-2026",
    model: "Image Tools",
    headline: "Style consistency is improving, but text is still a liar.",
    whatChanged: ["More consistent characters across generations", "Better style adherence", "Text in images still unreliable"],
    whoItAffects: ["Creators", "Brand pages", "Design workflows"],
    whatToDoNow: ["Use reference images when possible", "Keep style description short", "Don’t put important text inside images"],
    tldr: "Consistency up. Text still messy. Plan accordingly.",
    tags: ["image", "design"],
    updatedAtISO: "2026-01-20",
  },
  {
    id: "u3",
    slug: "agents-debugging",
    model: "Agents",
    headline: "Agent failures are mostly tool wiring, not model ‘intelligence’.",
    whatChanged: ["Most agent bugs traced to tool permissions, parsing, and retry logic", "Observability matters more than extra prompts"],
    whoItAffects: ["Builders", "Automation enthusiasts", "Anyone shipping agent products"],
    whatToDoNow: ["Add tracing", "Validate tool outputs", "Implement retries + backoff", "Write evals for edge cases"],
    tldr: "Your agent isn’t dumb. Your glue code is.",
    tags: ["agents", "dev"],
    updatedAtISO: "2026-01-19",
  },
  {
    id: "u4",
    slug: "seo-ai-sites",
    model: "SEO",
    headline: "AI content sites that win are ‘useful databases’, not blogs.",
    whatChanged: ["Sites with structured pages and internal linking perform better", "Thin posts with no unique value get ignored"],
    whoItAffects: ["Content site builders", "Affiliate + tool directory owners"],
    whatToDoNow: ["Build indexable pages per item", "Add collections and comparisons", "Add FAQ blocks", "Link everything internally"],
    tldr: "Databases + structure beat random posting.",
    tags: ["seo", "content"],
    updatedAtISO: "2026-01-18",
  },
  {
    id: "u5",
    slug: "copy-paste-prompts-fatigue",
    model: "Usage",
    headline: "People are fatigued by ‘prompt dumps’. They want packs with purpose.",
    whatChanged: ["Prompt libraries that add context + examples get saved more", "Generic prompt lists get skimmed then forgotten"],
    whoItAffects: ["Prompt creators", "Tool directories", "Newsletter writers"],
    whatToDoNow: ["Bundle prompts by outcome", "Add best-use scenarios", "Add variations and compatibility notes"],
    tldr: "Stop dumping prompts. Curate them like a sane person.",
    tags: ["prompts", "creator"],
    updatedAtISO: "2026-01-17",
  },
];
